In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
d0 = 'python for python'
d1 = 'python'
d2 = 'NLP'

In [3]:
string = [d0,d1,d2]

In [4]:
string

['python for python', 'python', 'NLP']

In [5]:
tfidf = TfidfVectorizer()

In [7]:
result = tfidf.fit_transform(string)

In [8]:
result

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [10]:
for ele1,ele2 in zip(tfidf.get_feature_names() , tfidf.idf_):
    print(ele1,':',ele2)

for : 1.6931471805599454
nlp : 1.6931471805599454
python : 1.2876820724517808


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [11]:
d0 = 'python1'
d1 = 'python2'
d2 = 'python3'
d3 = 'python4'

In [12]:
string = [d0,d1,d2,d3]

In [13]:
string

['python1', 'python2', 'python3', 'python4']

In [14]:
result = tfidf.fit_transform(string)

In [15]:
print(tfidf.vocabulary_)

{'python1': 0, 'python2': 1, 'python3': 2, 'python4': 3}


In [16]:
print(result)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [17]:
d0 = 'python for python'
d1 = 'python for python'

In [18]:
string = [d0,d1]

In [19]:
string

['python for python', 'python for python']

In [20]:
result = tfidf.fit_transform(string)

In [21]:
result

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [22]:
print(result)

  (0, 0)	0.4472135954999579
  (0, 1)	0.8944271909999159
  (1, 0)	0.4472135954999579
  (1, 1)	0.8944271909999159


In [23]:
print(tfidf.vocabulary_)

{'python': 1, 'for': 0}


In [24]:
string = ['Python python'] * 5

In [25]:
string

['Python python',
 'Python python',
 'Python python',
 'Python python',
 'Python python']

In [26]:
result = tfidf.fit_transform(string)

In [27]:
result

<5x1 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [28]:

tfidf.vocabulary_

{'python': 0}

In [29]:
print(result)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0


In [32]:
import numpy as np
from numpy.linalg import norm

In [34]:
d0 = np.array([2,1,2,3,2,9])
d1 = np.array([3,4,2,4,5,5])

In [35]:
d0

array([2, 1, 2, 3, 2, 9])

In [36]:
d1

array([3, 4, 2, 4, 5, 5])

In [37]:
cosine = np.dot( d0,d1) / (norm(d0) * norm(d1))

In [39]:
print("cosine similarity  : "  , cosine)

cosine similarity  :  0.8188504723485274


In [40]:
d0 = np.array( [ [2,1,2] , [3,2,9] , [-1,2,-3]  ]  )


In [41]:
d0

array([[ 2,  1,  2],
       [ 3,  2,  9],
       [-1,  2, -3]])

In [42]:
d1 = np.array([3,4,2])

In [43]:
d1

array([3, 4, 2])

In [44]:
cosine = np.dot(d0,d1) / (norm(d0 , axis=1) * norm(d1))

In [45]:
cosine

array([ 0.86657824,  0.67035541, -0.04962917])

In [ ]:
syantatic analyis
semantic analysis

In [47]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk

In [57]:
desc = pd.read_csv(r'C:\Users\Admin\Downloads\similar.csv',sep=",")

In [77]:
desc = desc[0:1000]

In [78]:
tfidf = TfidfVectorizer(stop_words = 'english')

In [79]:
doc_vector = tfidf.fit_transform(desc['description'])

In [81]:
doc_vector.shape

(1000, 3709)

In [82]:
doc_vector

<1000x3709 sparse matrix of type '<class 'numpy.float64'>'
	with 25578 stored elements in Compressed Sparse Row format>

In [85]:
results = []
query = 'i am looking  '
q_vector = tfidf.transform( [query] )


In [101]:
results.append(cosine_similarity(q_vector ,doc_vector.toarray() ))

In [89]:
# doc_vector.toarray()

In [95]:
cosine_similarity

<function sklearn.metrics.pairwise.cosine_similarity(X, Y=None, dense_output=True)>

In [102]:
results

for i in results[:10]:
    

[array([[0.0205479 , 0.        , 0.02144936, 0.        , 0.        ,
         0.        , 0.02423779, 0.02369976, 0.        , 0.02430211,
         0.        , 0.07579771, 0.13212529, 0.        , 0.02467011,
         0.02218864, 0.06113254, 0.02876157, 0.        , 0.        ,
         0.02111769, 0.02122138, 0.01973056, 0.02802087, 0.        ,
         0.02210447, 0.        , 0.03882259, 0.        , 0.02648713,
         0.        , 0.03029066, 0.        , 0.        , 0.03646871,
         0.        , 0.        , 0.0375988 , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.21817811, 0.        , 0.        ,
         0.06999979, 0.05916187, 0.02375653, 0.        , 0.03085437,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.06135046, 0.02350957, 0.05923926,
         0.        , 0.        , 0.02687893, 0.02886287, 0.04694952,
         0.        , 0.        , 0

In [104]:
import os
os.chdir(r'C:\Users\Admin\Downloads\py-master\py-master\NLP')